version: "3.9"
services:
  bot:
    build: .
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - CATALOG_PATH=${CATALOG_PATH:-data/fixed_catalog.yaml}
      - PARTNER_CODE=${PARTNER_CODE:-aff_123}
      - REDIRECT_BASE=${REDIRECT_BASE}
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    restart: unless-stopped

