[tool.ruff]
line-length = 100
target-version = "py311"
exclude = [
  ".skin-advisor/**",
]

[tool.black]
line-length = 100
target-version = ['py311']

[tool.mypy]
python_version = "3.11"
strict = false
warn_unused_ignores = true
warn_redundant_casts = true
warn_unreachable = true
ignore_missing_imports = true


