[build]
builder = "DOCKERFILE"
dockerfilePath = "./Dockerfile"

[deploy]
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
replicas = 1  # FORCE SINGLE INSTANCE to prevent Telegram conflicts
# Use Docker entrypoint - no startCommand needed

