[build]
builder = "DOCKERFILE"
dockerfilePath = "./Dockerfile"

[deploy]
startCommand = "python -m bot.main"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[service]
name = "skin-advisor"

[[service.volumes]]
mount_path = "/app/data"
source = "data-volume"

[[service.volumes]]
mount_path = "/app/logs"
source = "logs-volume"

