name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install black ruff

    - name: Format code with Black
      run: |
        echo "Formatting code with Black..."
        python -m black .

    - name: Lint with Ruff
      run: |
        echo "Linting with Ruff..."
        python -m ruff check --fix . || echo "⚠️  Ruff found issues but continuing..."

    - name: Security Check - No Raw Pin Calls
      run: |
        echo "🔍 Checking for raw pin/unpin calls (must use safe_pin_message)..."
        RAW_PINS=$(grep -r "pinChatMessage\|pin_chat_message\|unpin.*chat" --include="*.py" . | grep -v "safe_pin_message\|test_" | wc -l)
        if [ "$RAW_PINS" -gt 0 ]; then
          echo "❌ FOUND RAW PIN CALLS: $RAW_PINS occurrences"
          grep -r "pinChatMessage\|pin_chat_message\|unpin.*chat" --include="*.py" . | grep -v "safe_pin_message\|test_"
          exit 1
        else
          echo "✅ No raw pin calls found - security check passed"
        fi

    - name: Commit formatting changes
      run: |
        echo "Checking for formatting changes..."
        if [[ -n $(git status --porcelain) ]]; then
          echo "Committing formatting changes..."
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "style: auto-format code with black and ruff"
          git push origin HEAD
        else
          echo "No formatting changes needed"
        fi

    - name: Python syntax check
      run: |
        echo "Checking Python syntax..."
        python -m py_compile $(find . -name "*.py" -not -path "./tests/*" | head -20)

    - name: Run render smoke tests
      run: |
        echo "Running render smoke tests..."
        python -m pytest tests/test_render_smoke.py -v

    - name: Run flow smoke tests
      run: |
        echo "Running flow smoke tests..."
        python -m pytest tests/test_flow_smoke.py -v

    - name: Run cart integration tests
      run: |
        echo "Running cart integration tests..."
        python -m pytest tests/test_cart_integration.py -v || echo "⚠️  Cart tests failed but continuing..."

    - name: Run affiliate integration tests
      run: |
        echo "Running affiliate integration tests..."
        python -m pytest tests/test_affiliate_integration.py -v || echo "⚠️  Affiliate tests failed but continuing..."
