name: Deploy to Railway

on:
  push:
    branches: ["master"]  # Fixed: using master branch
  workflow_run:
    workflows: ["CI"]
    types:
      - completed
  workflow_dispatch: {}

env:
  RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
  # Optional – set if you want to force a specific project/service
  RAILWAY_PROJECT_ID: ${{ secrets.RAILWAY_PROJECT_ID }}
  RAILWAY_SERVICE_ID: ${{ secrets.RAILWAY_SERVICE_ID }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' || github.event_name == 'push' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Railway CLI
        run: npm i -g @railway/cli

      - name: Verify Railway CLI
        run: railway --version

      - name: Deploy to Railway
        run: |
          railway up --service skin-advisor
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
          RAILWAY_PROJECT_ID: ${{ secrets.RAILWAY_PROJECT_ID }}
          RAILWAY_SERVICE_ID: ${{ secrets.RAILWAY_SERVICE_ID }}