name: Deploy to Railway

on:
  push:
    branches: ["master"]  # Fixed: using master branch
  workflow_run:
    workflows: ["CI"]
    types:
      - completed
  workflow_dispatch: {}

# Environment variables for Railway
# Note: RAILWAY_TOKEN must be set in GitHub repository secrets

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: read
      id-token: write
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' || github.event_name == 'push' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Railway CLI
        run: |
          npm install -g @railway/cli
          echo "$(npm config get prefix)/bin" >> $GITHUB_PATH

      - name: Verify Railway CLI
        run: railway --version

      - name: Deploy to Railway
        run: |
          railway up
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}