name: Deploy to Render

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Deploy to Render
      run: |
        echo "🚀 Triggering Render deployment via API..."
        echo "Service ID: ${{ secrets.RENDER_SERVICE_ID }}"

        # Trigger deploy using Render API
        response=$(curl -s -o response.json -w "%{http_code}" \
          -X POST \
          -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
          -H "Content-Type: application/json" \
          https://api.render.com/v1/services/${{ secrets.RENDER_SERVICE_ID }}/deploys)

        if [ "$response" -eq 201 ]; then
          echo "✅ Deploy triggered successfully!"
          cat response.json
        else
          echo "❌ Failed to trigger deploy (HTTP $response)"
          cat response.json
          exit 1
        fi
