name: Deploy to Render

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Deploy to Render via Webhook
      run: |
        echo "🚀 Triggering Render deployment via webhook..."
        echo "Webhook URL: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}"

        # Trigger deploy using Render webhook
        if [ -n "${{ secrets.RENDER_DEPLOY_HOOK_URL }}" ]; then
          echo "Making webhook call to Render..."
          response=$(curl -s -o response.json -w "%{http_code}" \
            -X POST \
            -H "Content-Type: application/json" \
            "${{ secrets.RENDER_DEPLOY_HOOK_URL }}" 2>&1)

          echo "Webhook response code: $response"
          echo "Response body:"
          cat response.json || echo "No response body"

          if [ "$response" -eq 200 ] || [ "$response" -eq 201 ]; then
            echo "✅ Deploy triggered successfully via webhook!"
          else
            echo "❌ Failed to trigger deploy via webhook (HTTP $response)"
            echo "Falling back to manual notification..."
          fi
        else
          echo "⚠️  RENDER_DEPLOY_HOOK_URL not set, skipping automatic deploy"
          echo "Please deploy manually via Render dashboard"
        fi
